### ISSUE TITLE
Kth largest Element in array.

### ISSUE THREAD

**Issue by Kartikkh** [brotherpowers/go-algorithms#2]
This can be done in klog(n) using Heap sort.
where K is the kth largest element in array .

Create a Max Heap and iterate till k largest Element.

**Comment by harshvishu** [comment]
Thank you!
Will add another algorithm to perform `Kth largest number search` using a `Max Heap`. 

And you are always welcome to contribute, just follow the [guidelines](https://github.com/brotherpowers/go-algorithms/blob/master/CONTRIBUTING.md).

**Comment by harshvishu** [comment]
Added new function in **kthLargest.go** named `KthLargestUsingHeap()`. See this [a3479f7](https://github.com/brotherpowers/go-algorithms/commit/a3479f704923a582fc36d1c8e49855be98744777) for more info.
